### ISSUE TITLE
Selection Issue

### ISSUE THREAD

**Issue by abbasmashaddy72** [victorybiz/laravel-simple-select#12]
When Already selected Item is showing is [object Object]

This Only Occurs in Dependent Dropdowns Please Help

Please Check the Images
In This Have 2 Depended on One Each and 2 Completed Independent

![image](https://user-images.githubusercontent.com/55267488/188848343-c0ad6555-a617-4543-bd84-3f24a35444f3.png)

@dcblogdev 
@victorybiz

**Comment by puntogestioncl** [comment]
Hola, alguna solución para esto. Saludos

**Comment by puntogestioncl** [comment]
Hola, por si alguien le sirve. Cuando uno genera un array para cargar el componente, en mi caso, filtraba el array multidimensional, por lo cual los índices quedaban saltados.
`array:4 [
  1 => array:2 [
    "ID" => 3
    "Empresa" => "Empresa 1"
  ]
  0 => array:2 [
    "ID" => 2
    "Empresa" => "Empresa 2"
  ]
  3 => array:2 [
    "ID" => 5
    "Empresa" => "Empresa 4"
  ]
]`
Lo cual generaba el error, use **array_values** y le pase el array, se resetearon las indice, y ya no aparece el error.

Saludos
