### ISSUE TITLE
Simple Select: requires Popper

### ISSUE THREAD

**Issue by foxkyo** [victorybiz/laravel-simple-select#19]
fresh install from laravel 10

then install livewire 3
and [laravel-simple-select] with JavaScript Dependencies

the console.log shows
```
Uncaught TypeError: Laravel Simple Select: requires Popper (https://popper.js.org)
    at Proxy.popper ((index):1174:25)
    at (index):1052:32
```

my app.js code
```
import "./bootstrap";
import Alpine from 'alpinejs'
import { createPopper } from "@popperjs/core";

window.Alpine = Alpine;
Alpine.start()

window.**_createPopper_** = createPopper;
```
vscode shows
Property 'createPopper' does not exist on type 'Window & typeof globalThis'

excuse me 
how to solve it
thanks.

**Comment by NikarashiHatsu** [comment]
`window.createPopper = createPopper`, your code having the `**_createPopper_**`
