### ISSUE TITLE
Double dropdown arrow: how to fix?

### ISSUE THREAD

**Issue by MGeurts** [victorybiz/laravel-simple-select#21]
In a fresh Laravel 10 project, using TALL (including Tailwind), all Laravel-simple-select show a double dropdown arrow on the right.
Does anybody know how to fix this? Thanks.

![Simple-Select](https://github.com/victorybiz/laravel-simple-select/assets/5404867/83f8ffa7-03c5-4b28-aefa-557a72bada28)

**Comment by MGeurts** [comment]
Apparently, when I remove the `class="form-select"`, then the component renders like it should.

Can someone explain this? Thanks.

**Comment by NikarashiHatsu** [comment]
If you're using Bootstrap, `form-select` will append the caret icon within the CSS file. But also the `<x-simple-select />` component appends the caret icon as well, you might want to remove it manually after publishing the view.

**Comment by MGeurts** [comment]
I'm sorry. In the meantime I switched to TallStackUI components.
