### ISSUE TITLE
Alpine Expression Error: Unexpected template string

### ISSUE THREAD

**Issue by MGeurts** [victorybiz/laravel-simple-select#22]
The component generates a console error on the wire:key generation :

![laravel-simple-select-error](https://github.com/victorybiz/laravel-simple-select/assets/5404867/0632418f-6fdf-4d66-827f-05ff70957911)

**Comment by MGeurts** [comment]
I'm sorry. In the meantime I switched to TallStackUI components.

**Comment by shad3912** [comment]
For everybody looking for a solution, my quick and dirty method is this:

`:wire:key="id + Math.random().toString(36).substr(2, 8)"`

This way it is not using template strings and there is no problem finding the generateID() method.
