### ISSUE TITLE
HTML in option text-field?

### ISSUE THREAD

**Issue by MGeurts** [victorybiz/laravel-simple-select#24]
Is there a possibility to use HTML tags in the option **text-field** to highlight certain options?

Thanks.

**Comment by NikarashiHatsu** [comment]
Just publish the views, and edit the `simple-select.blade.php`, edit the code in line `<span x-text="getTextFromSelectedValue(value)"></span>` to `<span x-html="getTextFromSelectedValue(value)"></span>`. Alpine will render the expected HTML elements you provide.

**Comment by MGeurts** [comment]
I'm sorry. In the meantime I switched to TallStackUI components.
