### ISSUE TITLE
Package not maintained anymore?

### ISSUE THREAD

**Issue by MGeurts** [victorybiz/laravel-simple-select#25]
It seems this package is not maintained anymore.
Can the author confirm so we can look for an alternative?

Thanks.

**Comment by NikarashiHatsu** [comment]
I can't confirm if this package is not maintained anymore, but it seems like it's updated to support Livewire 3, although there's some errors in the console such as below, the package work as I expected.

<img width="498" alt="Screenshot 2024-06-21 at 16 24 51" src="https://github.com/victorybiz/laravel-simple-select/assets/43662951/3d8fddda-a24a-4d86-a29d-f8de6ab56074">

**Comment by MGeurts** [comment]
I'm sorry. In the meantime I switched to TallStackUI components.
