### ISSUE TITLE
show selected element

### ISSUE THREAD

**Issue by dcblogdev** [victorybiz/laravel-simple-select#3]
How do you show a standard selected value?

I have this usage:

```
<label>Supplier {{ $supplierId }}</label><br>
<x-simple-select name="supplierId" id="supplierId" wire:model="supplierId" :options="$suppliers" value-field='id' text-field='name' class="form-select" />
```

In my class I have mounted supplierId to an id I can see this if I render {{ $supplierId }} to the blade but the select does not pre-select the entry on load. The select menu remains blank until I manually select an item in the menu.

<img width="541" alt="Screenshot 2021-09-27 at 10 10 01" src="https://user-images.githubusercontent.com/1018170/134879259-3dcb28e3-25f4-4527-a977-e3f2a8a55a68.png">

**Comment by victorybiz** [comment]
In the component's mount method, ensure to assign the options first before assigning the model (selected value).

```php
public function mount($id)
{  
    $product = Product::findOrFail($id);

    $this->suppliers = Supply::get()->toArray(); // first, get list of options

    $this->supplierId = $product->supplier_id; // second, assign the selected suppier

}
```

**Comment by dcblogdev** [comment]
thank you, turns out to be a problem with how I was selecting the data I was using pluck changing how the data was loaded solved the issue in selecting an initial value

```php
Supplier::select('id', 'name')->orderBy('name')->get()->toArray()
```

Thank you! this package is great.
